version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ${CONF_PATH:-./conf}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${APP_DATA:-./app_data}/files:/app_data/files/
    depends_on:
      - web
    restart: ${RESTART:-always}

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather
    volumes:
      - ${APP_DATA:-./app_data}/files:/app_data/files
      - ${APP_DATA:-./app_data}/database:/app_data/database
    env_file:
      - .env
    restart: on-failure
    command: gunicorn weather.wsgi:application --bind 0.0.0.0:8000
